package com.twoto {		import com.twoto.content.controler.ContentControler;	import com.twoto.content.ui.ContentUI;	import com.twoto.dataModel.DataModel;	import com.twoto.global.DeeplinkUI;	import com.twoto.global.KeyInputUI;	import com.twoto.global.fonts.ExternalFonts;	import com.twoto.menu.controler.MenuControler;	import com.twoto.menu.model.MenuModel;	import com.twoto.menu.ui.MenuWithSearchUI;	import com.twoto.search.controler.SearchControler;	import com.twoto.search.model.SearchModel;	import com.twoto.submenu.controler.SubMenuControler;	import com.twoto.submenu.model.SubMenuModel;	import com.twoto.submenu.ui.BottomMenuUI;	import com.twoto.utils.FrameRateControler;	import com.twoto.utils.Log;		import flash.display.Sprite;	import flash.events.Event;		/**
	* 
	* @author Patrick Decaix
	* @email	patrick@twoto.com
	* @version 1.0
	*
	*/		public class Application extends Sprite {		
		//---------------------------------------------------------------------------
		// 	private variables
		//---------------------------------------------------------------------------		private var contentControler:ContentControler;		private var menuControler:MenuControler;		private var searchControler:SearchControler;		private var subMenuControler:SubMenuControler;				private var dataXML:XML;		private var dataModel:DataModel;		private var menuModel:MenuModel;		private var subMenuModel:SubMenuModel;		private var searchModel:SearchModel;				private var keyInputUI:KeyInputUI;		private var contentUI:ContentUI;		private var menuUI:MenuWithSearchUI;		private var deeplinkUI:DeeplinkUI;		private var bottomMenuUI:BottomMenuUI;				private var setFrameRate:FrameRateControler;				//---------------------------------------------------------------------------
		// 	constructor
		//---------------------------------------------------------------------------		public function Application(_dataXML:XML) {			dataXML =_dataXML;			Log.localtime();			initApp();		}		// initApp ----------------------------------------------------------------------		private function initApp():void{			dataModel = new DataModel(dataXML);						menuModel = new MenuModel();			subMenuModel = new SubMenuModel();			searchModel = new SearchModel(dataModel,menuModel);						searchControler = new SearchControler(searchModel,dataModel,menuModel);						contentUI = new ContentUI();			//contentControler = new ContentControler(contentUI,menuModel);			contentControler = new ContentControler(contentUI,menuModel);						menuControler = new MenuControler(menuModel,contentControler ,dataModel);			menuUI = new MenuWithSearchUI(menuModel,dataModel,menuControler,searchModel,searchControler);						keyInputUI = new KeyInputUI(searchModel,menuControler,searchControler,menuModel);						subMenuControler = new SubMenuControler(subMenuModel);			bottomMenuUI = new BottomMenuUI(menuModel,subMenuModel,dataModel,subMenuControler,this);						addChild(contentUI);			addChild(keyInputUI);			addChild(menuUI);			addChild(bottomMenuUI);						var initiateExternalFonts:ExternalFonts =new ExternalFonts();			/*			var newContent:contentTester = new contentTester(contentUI);			addChild(newContent);			*/			/*			var speedTest:Stats = new Stats();			addChild(speedTest);			*/				    	//			setFrameRate= new FrameRateControler();			setFrameRate.addEventListener(Event.COMPLETE,updateFrameRate);		}		private function updateFrameRate(evt:Event):void{			stage.frameRate = setFrameRate.maxiFrameRate;			//trace("update frameRate");		}	}}